version = 1

[install]
python.pkg-path = "python312"
pip.pkg-path = "python312Packages.pip"
anthropic.pkg-path = "python312Packages.anthropic"
click.pkg-path = "python312Packages.click"

[build]
claude.command = '''
mkdir -p $out/bin
cp claude.py $out/bin/claude
'''
